image: alpine
packages:
   - go
tasks:
   - setup: |
      go get -u github.com/golang/dep/cmd/dep/...
      curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
      dep ensure
   - check: |
      cd ari
      golangci-lint run
   - build: |
      go build
      go build stdbus
      go build rid
      go build client/native
      go build ext/audiouri
      go build ext/bridgemon
      go build ext/keyfilter
      go build ext/play
      go build ext/record
