language: go
go:
   - "1.10"
install:
   - go get -v github.com/Masterminds/glide
   - glide install
   - go get -u github.com/alecthomas/gometalinter/...
   - go get -u github.com/kevinburke/write_mailmap
   - gometalinter --install
script: make ci
