version: '2'

services:
  asterisk:
    build: ./asterisk
    ports:
     - "8088:8088"
  nats:
    image: nats
    ports:
     - "4222:4222"
  natsgw:
    build: ./natsgw
    links:
      - asterisk
      - nats
  senddtmf-start:
    build: ./sendDtmf-nats
    links:
      - nats
